// Country data with phone codes and flags
export const countries = [
  { code: "MX", name: "México", nameEn: "Mexico", phone: "+52", flag: "🇲🇽" },
  { code: "US", name: "Estados Unidos", nameEn: "United States", phone: "+1", flag: "🇺🇸" },
  { code: "CA", name: "Canadá", nameEn: "Canada", phone: "+1", flag: "🇨🇦" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala", phone: "+502", flag: "🇬🇹" },
  { code: "BZ", name: "Belice", nameEn: "Belize", phone: "+501", flag: "🇧🇿" },
  { code: "SV", name: "El Salvador", nameEn: "El Salvador", phone: "+503", flag: "🇸🇻" },
  { code: "HN", name: "Honduras", nameEn: "Honduras", phone: "+504", flag: "🇭🇳" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua", phone: "+505", flag: "🇳🇮" },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica", phone: "+506", flag: "🇨🇷" },
  { code: "PA", name: "Panamá", nameEn: "Panama", phone: "+507", flag: "🇵🇦" },
  { code: "CO", name: "Colombia", nameEn: "Colombia", phone: "+57", flag: "🇨🇴" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela", phone: "+58", flag: "🇻🇪" },
  { code: "EC", name: "Ecuador", nameEn: "Ecuador", phone: "+593", flag: "🇪🇨" },
  { code: "PE", name: "Perú", nameEn: "Peru", phone: "+51", flag: "🇵🇪" },
  { code: "BR", name: "Brasil", nameEn: "Brazil", phone: "+55", flag: "🇧🇷" },
  { code: "BO", name: "Bolivia", nameEn: "Bolivia", phone: "+591", flag: "🇧🇴" },
  { code: "CL", name: "Chile", nameEn: "Chile", phone: "+56", flag: "🇨🇱" },
  { code: "AR", name: "Argentina", nameEn: "Argentina", phone: "+54", flag: "🇦🇷" },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay", phone: "+598", flag: "🇺🇾" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay", phone: "+595", flag: "🇵🇾" },
  { code: "CU", name: "Cuba", nameEn: "Cuba", phone: "+53", flag: "🇨🇺" },
  { code: "DO", name: "República Dominicana", nameEn: "Dominican Republic", phone: "+1", flag: "🇩🇴" },
  { code: "PR", name: "Puerto Rico", nameEn: "Puerto Rico", phone: "+1", flag: "🇵🇷" },
  { code: "HT", name: "Haití", nameEn: "Haiti", phone: "+509", flag: "🇭🇹" },
  { code: "JM", name: "Jamaica", nameEn: "Jamaica", phone: "+1", flag: "🇯🇲" },
  { code: "TT", name: "Trinidad y Tobago", nameEn: "Trinidad and Tobago", phone: "+1", flag: "🇹🇹" },
  { code: "ES", name: "España", nameEn: "Spain", phone: "+34", flag: "🇪🇸" },
  { code: "PT", name: "Portugal", nameEn: "Portugal", phone: "+351", flag: "🇵🇹" },
  { code: "FR", name: "Francia", nameEn: "France", phone: "+33", flag: "🇫🇷" },
  { code: "DE", name: "Alemania", nameEn: "Germany", phone: "+49", flag: "🇩🇪" },
  { code: "IT", name: "Italia", nameEn: "Italy", phone: "+39", flag: "🇮🇹" },
  { code: "GB", name: "Reino Unido", nameEn: "United Kingdom", phone: "+44", flag: "🇬🇧" },
  { code: "IE", name: "Irlanda", nameEn: "Ireland", phone: "+353", flag: "🇮🇪" },
  { code: "NL", name: "Países Bajos", nameEn: "Netherlands", phone: "+31", flag: "🇳🇱" },
  { code: "BE", name: "Bélgica", nameEn: "Belgium", phone: "+32", flag: "🇧🇪" },
  { code: "CH", name: "Suiza", nameEn: "Switzerland", phone: "+41", flag: "🇨🇭" },
  { code: "AT", name: "Austria", nameEn: "Austria", phone: "+43", flag: "🇦🇹" },
  { code: "SE", name: "Suecia", nameEn: "Sweden", phone: "+46", flag: "🇸🇪" },
  { code: "NO", name: "Noruega", nameEn: "Norway", phone: "+47", flag: "🇳🇴" },
  { code: "DK", name: "Dinamarca", nameEn: "Denmark", phone: "+45", flag: "🇩🇰" },
  { code: "FI", name: "Finlandia", nameEn: "Finland", phone: "+358", flag: "🇫🇮" },
  { code: "PL", name: "Polonia", nameEn: "Poland", phone: "+48", flag: "🇵🇱" },
  { code: "CZ", name: "República Checa", nameEn: "Czech Republic", phone: "+420", flag: "🇨🇿" },
  { code: "RO", name: "Rumania", nameEn: "Romania", phone: "+40", flag: "🇷🇴" },
  { code: "HU", name: "Hungría", nameEn: "Hungary", phone: "+36", flag: "🇭🇺" },
  { code: "GR", name: "Grecia", nameEn: "Greece", phone: "+30", flag: "🇬🇷" },
  { code: "TR", name: "Turquía", nameEn: "Turkey", phone: "+90", flag: "🇹🇷" },
  { code: "RU", name: "Rusia", nameEn: "Russia", phone: "+7", flag: "🇷🇺" },
  { code: "UA", name: "Ucrania", nameEn: "Ukraine", phone: "+380", flag: "🇺🇦" },
  { code: "JP", name: "Japón", nameEn: "Japan", phone: "+81", flag: "🇯🇵" },
  { code: "CN", name: "China", nameEn: "China", phone: "+86", flag: "🇨🇳" },
  { code: "KR", name: "Corea del Sur", nameEn: "South Korea", phone: "+82", flag: "🇰🇷" },
  { code: "IN", name: "India", nameEn: "India", phone: "+91", flag: "🇮🇳" },
  { code: "PH", name: "Filipinas", nameEn: "Philippines", phone: "+63", flag: "🇵🇭" },
  { code: "TH", name: "Tailandia", nameEn: "Thailand", phone: "+66", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam", phone: "+84", flag: "🇻🇳" },
  { code: "ID", name: "Indonesia", nameEn: "Indonesia", phone: "+62", flag: "🇮🇩" },
  { code: "MY", name: "Malasia", nameEn: "Malaysia", phone: "+60", flag: "🇲🇾" },
  { code: "SG", name: "Singapur", nameEn: "Singapore", phone: "+65", flag: "🇸🇬" },
  { code: "AU", name: "Australia", nameEn: "Australia", phone: "+61", flag: "🇦🇺" },
  { code: "NZ", name: "Nueva Zelanda", nameEn: "New Zealand", phone: "+64", flag: "🇳🇿" },
  { code: "ZA", name: "Sudáfrica", nameEn: "South Africa", phone: "+27", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria", phone: "+234", flag: "🇳🇬" },
  { code: "EG", name: "Egipto", nameEn: "Egypt", phone: "+20", flag: "🇪🇬" },
  { code: "KE", name: "Kenia", nameEn: "Kenya", phone: "+254", flag: "🇰🇪" },
  { code: "MA", name: "Marruecos", nameEn: "Morocco", phone: "+212", flag: "🇲🇦" },
  { code: "SA", name: "Arabia Saudita", nameEn: "Saudi Arabia", phone: "+966", flag: "🇸🇦" },
  { code: "AE", name: "Emiratos Árabes Unidos", nameEn: "United Arab Emirates", phone: "+971", flag: "🇦🇪" },
  { code: "IL", name: "Israel", nameEn: "Israel", phone: "+972", flag: "🇮🇱" },
  { code: "PK", name: "Pakistán", nameEn: "Pakistan", phone: "+92", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", nameEn: "Bangladesh", phone: "+880", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", nameEn: "Sri Lanka", phone: "+94", flag: "🇱🇰" },
  { code: "NP", name: "Nepal", nameEn: "Nepal", phone: "+977", flag: "🇳🇵" },
  { code: "TW", name: "Taiwán", nameEn: "Taiwan", phone: "+886", flag: "🇹🇼" },
  { code: "HK", name: "Hong Kong", nameEn: "Hong Kong", phone: "+852", flag: "🇭🇰" },
];

export function getCountryByCode(code) {
  return countries.find(c => c.code === code);
}
