// Country data — MIRROR of backend/data/countries.py (SINGLE SOURCE OF TRUTH)
// If you add/edit countries, update backend/data/countries.py to match.
// Fields: code, name (es), nameEn, phone (prefix), flag, currency, currencySymbol, timezone, language

export const countries = [
  { code: "MX", name: "México", nameEn: "Mexico", phone: "+52", flag: "🇲🇽", currency: "MXN", currencySymbol: "$", timezone: "America/Mexico_City", language: "es" },
  { code: "US", name: "Estados Unidos", nameEn: "United States", phone: "+1", flag: "🇺🇸", currency: "USD", currencySymbol: "$", timezone: "America/New_York", language: "en" },
  { code: "CA", name: "Canadá", nameEn: "Canada", phone: "+1", flag: "🇨🇦", currency: "CAD", currencySymbol: "$", timezone: "America/Toronto", language: "en" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala", phone: "+502", flag: "🇬🇹", currency: "GTQ", currencySymbol: "Q", timezone: "America/Guatemala", language: "es" },
  { code: "BZ", name: "Belice", nameEn: "Belize", phone: "+501", flag: "🇧🇿", currency: "BZD", currencySymbol: "$", timezone: "America/Belize", language: "en" },
  { code: "SV", name: "El Salvador", nameEn: "El Salvador", phone: "+503", flag: "🇸🇻", currency: "USD", currencySymbol: "$", timezone: "America/El_Salvador", language: "es" },
  { code: "HN", name: "Honduras", nameEn: "Honduras", phone: "+504", flag: "🇭🇳", currency: "HNL", currencySymbol: "L", timezone: "America/Tegucigalpa", language: "es" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua", phone: "+505", flag: "🇳🇮", currency: "NIO", currencySymbol: "C$", timezone: "America/Managua", language: "es" },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica", phone: "+506", flag: "🇨🇷", currency: "CRC", currencySymbol: "₡", timezone: "America/Costa_Rica", language: "es" },
  { code: "PA", name: "Panamá", nameEn: "Panama", phone: "+507", flag: "🇵🇦", currency: "PAB", currencySymbol: "B/.", timezone: "America/Panama", language: "es" },
  { code: "CO", name: "Colombia", nameEn: "Colombia", phone: "+57", flag: "🇨🇴", currency: "COP", currencySymbol: "$", timezone: "America/Bogota", language: "es" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela", phone: "+58", flag: "🇻🇪", currency: "VES", currencySymbol: "Bs.", timezone: "America/Caracas", language: "es" },
  { code: "EC", name: "Ecuador", nameEn: "Ecuador", phone: "+593", flag: "🇪🇨", currency: "USD", currencySymbol: "$", timezone: "America/Guayaquil", language: "es" },
  { code: "PE", name: "Perú", nameEn: "Peru", phone: "+51", flag: "🇵🇪", currency: "PEN", currencySymbol: "S/", timezone: "America/Lima", language: "es" },
  { code: "BR", name: "Brasil", nameEn: "Brazil", phone: "+55", flag: "🇧🇷", currency: "BRL", currencySymbol: "R$", timezone: "America/Sao_Paulo", language: "pt" },
  { code: "BO", name: "Bolivia", nameEn: "Bolivia", phone: "+591", flag: "🇧🇴", currency: "BOB", currencySymbol: "Bs", timezone: "America/La_Paz", language: "es" },
  { code: "CL", name: "Chile", nameEn: "Chile", phone: "+56", flag: "🇨🇱", currency: "CLP", currencySymbol: "$", timezone: "America/Santiago", language: "es" },
  { code: "AR", name: "Argentina", nameEn: "Argentina", phone: "+54", flag: "🇦🇷", currency: "ARS", currencySymbol: "$", timezone: "America/Argentina/Buenos_Aires", language: "es" },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay", phone: "+598", flag: "🇺🇾", currency: "UYU", currencySymbol: "$U", timezone: "America/Montevideo", language: "es" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay", phone: "+595", flag: "🇵🇾", currency: "PYG", currencySymbol: "₲", timezone: "America/Asuncion", language: "es" },
  { code: "CU", name: "Cuba", nameEn: "Cuba", phone: "+53", flag: "🇨🇺", currency: "CUP", currencySymbol: "$", timezone: "America/Havana", language: "es" },
  { code: "DO", name: "República Dominicana", nameEn: "Dominican Republic", phone: "+1", flag: "🇩🇴", currency: "DOP", currencySymbol: "RD$", timezone: "America/Santo_Domingo", language: "es" },
  { code: "PR", name: "Puerto Rico", nameEn: "Puerto Rico", phone: "+1", flag: "🇵🇷", currency: "USD", currencySymbol: "$", timezone: "America/Puerto_Rico", language: "es" },
  { code: "HT", name: "Haití", nameEn: "Haiti", phone: "+509", flag: "🇭🇹", currency: "HTG", currencySymbol: "G", timezone: "America/Port-au-Prince", language: "fr" },
  { code: "JM", name: "Jamaica", nameEn: "Jamaica", phone: "+1", flag: "🇯🇲", currency: "JMD", currencySymbol: "J$", timezone: "America/Jamaica", language: "en" },
  { code: "TT", name: "Trinidad y Tobago", nameEn: "Trinidad and Tobago", phone: "+1", flag: "🇹🇹", currency: "TTD", currencySymbol: "TT$", timezone: "America/Port_of_Spain", language: "en" },
  { code: "ES", name: "España", nameEn: "Spain", phone: "+34", flag: "🇪🇸", currency: "EUR", currencySymbol: "€", timezone: "Europe/Madrid", language: "es" },
  { code: "PT", name: "Portugal", nameEn: "Portugal", phone: "+351", flag: "🇵🇹", currency: "EUR", currencySymbol: "€", timezone: "Europe/Lisbon", language: "pt" },
  { code: "FR", name: "Francia", nameEn: "France", phone: "+33", flag: "🇫🇷", currency: "EUR", currencySymbol: "€", timezone: "Europe/Paris", language: "fr" },
  { code: "DE", name: "Alemania", nameEn: "Germany", phone: "+49", flag: "🇩🇪", currency: "EUR", currencySymbol: "€", timezone: "Europe/Berlin", language: "de" },
  { code: "IT", name: "Italia", nameEn: "Italy", phone: "+39", flag: "🇮🇹", currency: "EUR", currencySymbol: "€", timezone: "Europe/Rome", language: "it" },
  { code: "GB", name: "Reino Unido", nameEn: "United Kingdom", phone: "+44", flag: "🇬🇧", currency: "GBP", currencySymbol: "£", timezone: "Europe/London", language: "en" },
  { code: "IE", name: "Irlanda", nameEn: "Ireland", phone: "+353", flag: "🇮🇪", currency: "EUR", currencySymbol: "€", timezone: "Europe/Dublin", language: "en" },
  { code: "NL", name: "Países Bajos", nameEn: "Netherlands", phone: "+31", flag: "🇳🇱", currency: "EUR", currencySymbol: "€", timezone: "Europe/Amsterdam", language: "nl" },
  { code: "BE", name: "Bélgica", nameEn: "Belgium", phone: "+32", flag: "🇧🇪", currency: "EUR", currencySymbol: "€", timezone: "Europe/Brussels", language: "fr" },
  { code: "CH", name: "Suiza", nameEn: "Switzerland", phone: "+41", flag: "🇨🇭", currency: "CHF", currencySymbol: "CHF", timezone: "Europe/Zurich", language: "de" },
  { code: "AT", name: "Austria", nameEn: "Austria", phone: "+43", flag: "🇦🇹", currency: "EUR", currencySymbol: "€", timezone: "Europe/Vienna", language: "de" },
  { code: "SE", name: "Suecia", nameEn: "Sweden", phone: "+46", flag: "🇸🇪", currency: "SEK", currencySymbol: "kr", timezone: "Europe/Stockholm", language: "sv" },
  { code: "NO", name: "Noruega", nameEn: "Norway", phone: "+47", flag: "🇳🇴", currency: "NOK", currencySymbol: "kr", timezone: "Europe/Oslo", language: "no" },
  { code: "DK", name: "Dinamarca", nameEn: "Denmark", phone: "+45", flag: "🇩🇰", currency: "DKK", currencySymbol: "kr", timezone: "Europe/Copenhagen", language: "da" },
  { code: "FI", name: "Finlandia", nameEn: "Finland", phone: "+358", flag: "🇫🇮", currency: "EUR", currencySymbol: "€", timezone: "Europe/Helsinki", language: "fi" },
  { code: "PL", name: "Polonia", nameEn: "Poland", phone: "+48", flag: "🇵🇱", currency: "PLN", currencySymbol: "zł", timezone: "Europe/Warsaw", language: "pl" },
  { code: "CZ", name: "República Checa", nameEn: "Czech Republic", phone: "+420", flag: "🇨🇿", currency: "CZK", currencySymbol: "Kč", timezone: "Europe/Prague", language: "cs" },
  { code: "RO", name: "Rumania", nameEn: "Romania", phone: "+40", flag: "🇷🇴", currency: "RON", currencySymbol: "lei", timezone: "Europe/Bucharest", language: "ro" },
  { code: "HU", name: "Hungría", nameEn: "Hungary", phone: "+36", flag: "🇭🇺", currency: "HUF", currencySymbol: "Ft", timezone: "Europe/Budapest", language: "hu" },
  { code: "GR", name: "Grecia", nameEn: "Greece", phone: "+30", flag: "🇬🇷", currency: "EUR", currencySymbol: "€", timezone: "Europe/Athens", language: "el" },
  { code: "TR", name: "Turquía", nameEn: "Turkey", phone: "+90", flag: "🇹🇷", currency: "TRY", currencySymbol: "₺", timezone: "Europe/Istanbul", language: "tr" },
  { code: "RU", name: "Rusia", nameEn: "Russia", phone: "+7", flag: "🇷🇺", currency: "RUB", currencySymbol: "₽", timezone: "Europe/Moscow", language: "ru" },
  { code: "UA", name: "Ucrania", nameEn: "Ukraine", phone: "+380", flag: "🇺🇦", currency: "UAH", currencySymbol: "₴", timezone: "Europe/Kyiv", language: "uk" },
  { code: "JP", name: "Japón", nameEn: "Japan", phone: "+81", flag: "🇯🇵", currency: "JPY", currencySymbol: "¥", timezone: "Asia/Tokyo", language: "ja" },
  { code: "CN", name: "China", nameEn: "China", phone: "+86", flag: "🇨🇳", currency: "CNY", currencySymbol: "¥", timezone: "Asia/Shanghai", language: "zh" },
  { code: "KR", name: "Corea del Sur", nameEn: "South Korea", phone: "+82", flag: "🇰🇷", currency: "KRW", currencySymbol: "₩", timezone: "Asia/Seoul", language: "ko" },
  { code: "IN", name: "India", nameEn: "India", phone: "+91", flag: "🇮🇳", currency: "INR", currencySymbol: "₹", timezone: "Asia/Kolkata", language: "hi" },
  { code: "PH", name: "Filipinas", nameEn: "Philippines", phone: "+63", flag: "🇵🇭", currency: "PHP", currencySymbol: "₱", timezone: "Asia/Manila", language: "en" },
  { code: "TH", name: "Tailandia", nameEn: "Thailand", phone: "+66", flag: "🇹🇭", currency: "THB", currencySymbol: "฿", timezone: "Asia/Bangkok", language: "th" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam", phone: "+84", flag: "🇻🇳", currency: "VND", currencySymbol: "₫", timezone: "Asia/Ho_Chi_Minh", language: "vi" },
  { code: "ID", name: "Indonesia", nameEn: "Indonesia", phone: "+62", flag: "🇮🇩", currency: "IDR", currencySymbol: "Rp", timezone: "Asia/Jakarta", language: "id" },
  { code: "MY", name: "Malasia", nameEn: "Malaysia", phone: "+60", flag: "🇲🇾", currency: "MYR", currencySymbol: "RM", timezone: "Asia/Kuala_Lumpur", language: "ms" },
  { code: "SG", name: "Singapur", nameEn: "Singapore", phone: "+65", flag: "🇸🇬", currency: "SGD", currencySymbol: "S$", timezone: "Asia/Singapore", language: "en" },
  { code: "AU", name: "Australia", nameEn: "Australia", phone: "+61", flag: "🇦🇺", currency: "AUD", currencySymbol: "$", timezone: "Australia/Sydney", language: "en" },
  { code: "NZ", name: "Nueva Zelanda", nameEn: "New Zealand", phone: "+64", flag: "🇳🇿", currency: "NZD", currencySymbol: "$", timezone: "Pacific/Auckland", language: "en" },
  { code: "ZA", name: "Sudáfrica", nameEn: "South Africa", phone: "+27", flag: "🇿🇦", currency: "ZAR", currencySymbol: "R", timezone: "Africa/Johannesburg", language: "en" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria", phone: "+234", flag: "🇳🇬", currency: "NGN", currencySymbol: "₦", timezone: "Africa/Lagos", language: "en" },
  { code: "EG", name: "Egipto", nameEn: "Egypt", phone: "+20", flag: "🇪🇬", currency: "EGP", currencySymbol: "£", timezone: "Africa/Cairo", language: "ar" },
  { code: "KE", name: "Kenia", nameEn: "Kenya", phone: "+254", flag: "🇰🇪", currency: "KES", currencySymbol: "KSh", timezone: "Africa/Nairobi", language: "en" },
  { code: "MA", name: "Marruecos", nameEn: "Morocco", phone: "+212", flag: "🇲🇦", currency: "MAD", currencySymbol: "د.م.", timezone: "Africa/Casablanca", language: "ar" },
  { code: "SA", name: "Arabia Saudita", nameEn: "Saudi Arabia", phone: "+966", flag: "🇸🇦", currency: "SAR", currencySymbol: "﷼", timezone: "Asia/Riyadh", language: "ar" },
  { code: "AE", name: "Emiratos Árabes Unidos", nameEn: "United Arab Emirates", phone: "+971", flag: "🇦🇪", currency: "AED", currencySymbol: "د.إ", timezone: "Asia/Dubai", language: "ar" },
  { code: "IL", name: "Israel", nameEn: "Israel", phone: "+972", flag: "🇮🇱", currency: "ILS", currencySymbol: "₪", timezone: "Asia/Jerusalem", language: "he" },
  { code: "PK", name: "Pakistán", nameEn: "Pakistan", phone: "+92", flag: "🇵🇰", currency: "PKR", currencySymbol: "₨", timezone: "Asia/Karachi", language: "ur" },
  { code: "BD", name: "Bangladesh", nameEn: "Bangladesh", phone: "+880", flag: "🇧🇩", currency: "BDT", currencySymbol: "৳", timezone: "Asia/Dhaka", language: "bn" },
  { code: "LK", name: "Sri Lanka", nameEn: "Sri Lanka", phone: "+94", flag: "🇱🇰", currency: "LKR", currencySymbol: "Rs", timezone: "Asia/Colombo", language: "si" },
  { code: "NP", name: "Nepal", nameEn: "Nepal", phone: "+977", flag: "🇳🇵", currency: "NPR", currencySymbol: "रू", timezone: "Asia/Kathmandu", language: "ne" },
  { code: "TW", name: "Taiwán", nameEn: "Taiwan", phone: "+886", flag: "🇹🇼", currency: "TWD", currencySymbol: "NT$", timezone: "Asia/Taipei", language: "zh" },
  { code: "HK", name: "Hong Kong", nameEn: "Hong Kong", phone: "+852", flag: "🇭🇰", currency: "HKD", currencySymbol: "HK$", timezone: "Asia/Hong_Kong", language: "zh" },
];

export function getCountryByCode(code) {
  return countries.find(c => c.code === code);
}
